.PHONY: init
init:
	npm i

.PHONY: run
run:
	npm start

.PHONY: lint
lint:
	npm run lint

.PHONY: build
build:
	npm run build

.PHONY: rm
rm:
	rm -f db.sqlite

.PHONY: migrate
migrate:
	npm run migrate

.DEFAULT_GOAL: init

