version: '3'
services:
  
  nosql-db1:
    image: mongo
    ports:
      - "27017:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  booking:
    build:
      dockerfile: Dockerfile
      context: ./Booking
    container_name: Booking
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db1"
    volumes:
      - .:/app
      - /app/Booking/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db1"
    volumes:
      - .:/app
      - /app/customer/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - booking
      - customer
    ports:
      - "80:80"
 