version: '3.8'

services:
  pg:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  bookings:
    build: ./booking
    working_dir: /home/app
    command: npm start
    expose:
      - 3000

  hotels:
    build: ./hotels
    working_dir: /home/app
    command: npm start
    expose:
      - 3000

  nginx:
    image: nginx:1.21-alpine-perl
    depends_on:
      - bookings
      - hotels
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - '80:80'

volumes:
  pg:
  pgadmin:
